FROM rust:1.77.2-alpine3.19

RUN apk add --no-cache clang16-dev

COPY --from=musl-cross-scip-test /work/scip_install /scip_install
WORKDIR /work
COPY . .

# Disable forcing static linking always (as clang can't be linked otherwise)
# See here for more info:
# https://github.com/rust-lang/docker-rust/issues/167#issuecomment-1970538925
ENV RUSTFLAGS='-C target-feature=-crt-static'

ENV SCIPOPTDIR=/scip_install
RUN cargo build --release
RUN cargo run --release --example create
