version: 2.1

executors:
  linux: # a Linux VM running Ubuntu 20.04
    machine:
      image: ubuntu-2204:current
  macos: # macos executor running Xcode
    macos:
      xcode: 15.2.0

jobs:
  build:
    parameters:
      executor:
        type: executor
        default: linux
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  builds:
    jobs:
      - build:
          matrix:
            parameters:
              executor: [linux, macos]
