version: 2.1

executors:
  linux:
    machine:
      image: ubuntu-2204:current
  macos:
    macos:
      xcode: 15.2.0

jobs:
  build:
    parameters:
      executor:
        type: executor
        default: linux
      resource_class:
        type: string
        default: arm.large
    executor: << parameters.executor >>
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  builds:
    jobs:
      - build:
          matrix:
            parameters:
              executor: [linux]
              resource_class: [large, arm.large]
      - build:
          matrix:
            parameters:
              executor: [macos]
              # TODO: Add macos.m1 in May when it becomes free for basic plan
              # resource_class: [macos.x86.medium.gen2, macos.m1.medium.gen1]
              resource_class: [macos.x86.medium.gen2]
