version: 2.1

orbs:
  rust: circleci/rust@1.6.1

executors:
  linux:
    machine:
      image: ubuntu-2204:current

jobs:
  build:
    parameters:
      executor:
        type: executor
        default: linux
      resource_class:
        type: string
        default: arm.large
    docker:
      - image: cimg/rust:1.77.2
    executor: docker
    resource_class: << parameters.resource_class >>
    steps:
      - run: rustc --version

workflows:
  builds:
    jobs:
      - build:
          matrix:
            parameters:
              resource_class: [large, arm.large]
