version: 2.1

orbs:
  rust: circleci/rust@1.6.1

executors:
  docker:
    docker:
      - image: cimg/rust:1.77.2
  linux:
    machine:
      image: ubuntu-2204:current

jobs:
  build:
    parameters:
      feature:
        type: string
        default: bundled
      resource_class:
        type: string
        default: arm.large
    executor: docker
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run: cargo build -F << parameters.feature >>

workflows:
  builds:
    jobs:
      - build:
          matrix:
            parameters:
              resource_class: [large, arm.large]
              feature: [bundled, from-source]
